services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    platform: linux/amd64
    container_name: contatos_api
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Contatos@123"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    restart: always

volumes:
  sqlserver_data: